//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIShopKaro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public System.Guid ID { get; set; }
        public System.Guid PRODUCTID { get; set; }
        public int QUANTITY { get; set; }
        public System.Guid BUYERID { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
