//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIShopKaro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORy
    {
        public CATEGORy()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
            this.SERVICES = new HashSet<SERVICE>();
        }
    
        public System.Guid ID { get; set; }
        public string NAME { get; set; }
        public bool SERVICE { get; set; }
    
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
        public virtual ICollection<SERVICE> SERVICES { get; set; }
    }
}
