//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIShopKaro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public ORDER()
        {
            this.ORDERPRODUCTS = new HashSet<ORDERPRODUCT>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid BUYERID { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public string PLACE { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public int PINCODE { get; set; }
        public decimal TOTATPRICE { get; set; }
        public Nullable<bool> ISSERVICE { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
    
        public virtual ICollection<ORDERPRODUCT> ORDERPRODUCTS { get; set; }
        public virtual USER USER { get; set; }
    }
}
