//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIShopKaro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW
    {
        public System.Guid? ID { get; set; }
        public Nullable<System.Guid> PRODUCTID { get; set; }
        public Nullable<System.Guid> SERVICEID { get; set; }
        public Nullable<System.Guid> REVIEWERID { get; set; }
        public Nullable<int> RATING { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<System.DateTime> REVIEWDATE { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual USER USER { get; set; }
        public virtual SERVICE SERVICE { get; set; }
    }
}
