//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIShopKaro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public ROLE()
        {
            this.USERS = new HashSet<USER>();
        }
    
        public int ROLEID { get; set; }
        public string ROLENAME { get; set; }
    
        public virtual ICollection<USER> USERS { get; set; }
    }
}
