//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIShopKaro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICEORDER
    {
        public System.Guid SERVICEID { get; set; }
        public System.Guid BUYERID { get; set; }
        public Nullable<System.DateTime> Orderdate { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual SERVICE SERVICE { get; set; }
    }
}
