//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIShopKaro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.CARTs = new HashSet<CART>();
            this.ORDERS = new HashSet<ORDER>();
            this.PRODUCTS = new HashSet<PRODUCT>();
            this.REVIEWS = new HashSet<REVIEW>();
            this.SERVICEORDERs = new HashSet<SERVICEORDER>();
            this.SERVICES = new HashSet<SERVICE>();
        }
    
        public System.Guid ID { get; set; }
        public int ROLEID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string NAME { get; set; }
        public string GENDER { get; set; }
        public string CONTACTNUMBER { get; set; }
        public string EMAILID { get; set; }
        public string PLACE { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public Nullable<int> PINCODE { get; set; }
    
        public virtual ICollection<CART> CARTs { get; set; }
        public virtual ICollection<ORDER> ORDERS { get; set; }
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
        public virtual ICollection<REVIEW> REVIEWS { get; set; }
        public virtual ROLE ROLE { get; set; }
        public virtual ICollection<SERVICEORDER> SERVICEORDERs { get; set; }
        public virtual ICollection<SERVICE> SERVICES { get; set; }
    }
}
